### ISSUE TITLE
Herokuからsubpackageをロードできていない

### ISSUE THREAD

**Issue by equanz** [equanz/key-notify-server#6]
[view the build log](https://dashboard.heroku.com/apps/key-notify-server/activity/builds/9c80fccc-492c-4a6a-8f90-a84c675b7f0a)より，

Herokuにて`main` パッケージから `sql_query` パッケージをロードできていない

**Comment by rikyuusima** [comment]
Dockerコンテナ化を検討してもよいのではないかと

**Comment by equanz** [comment]
#8にて対応し，マージ完了
